# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/onefore/projects/course-paper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/onefore/projects/course-paper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/onefore/projects/course-paper/CMakeFiles /home/onefore/projects/course-paper//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/onefore/projects/course-paper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named course-paper

# Build rule for target.
course-paper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 course-paper
.PHONY : course-paper

# fast build rule for target.
course-paper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/build
.PHONY : course-paper/fast

UI/sources/evolution.o: UI/sources/evolution.cpp.o
.PHONY : UI/sources/evolution.o

# target to build an object file
UI/sources/evolution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/evolution.cpp.o
.PHONY : UI/sources/evolution.cpp.o

UI/sources/evolution.i: UI/sources/evolution.cpp.i
.PHONY : UI/sources/evolution.i

# target to preprocess a source file
UI/sources/evolution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/evolution.cpp.i
.PHONY : UI/sources/evolution.cpp.i

UI/sources/evolution.s: UI/sources/evolution.cpp.s
.PHONY : UI/sources/evolution.s

# target to generate assembly for a file
UI/sources/evolution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/evolution.cpp.s
.PHONY : UI/sources/evolution.cpp.s

UI/sources/info_page.o: UI/sources/info_page.cpp.o
.PHONY : UI/sources/info_page.o

# target to build an object file
UI/sources/info_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/info_page.cpp.o
.PHONY : UI/sources/info_page.cpp.o

UI/sources/info_page.i: UI/sources/info_page.cpp.i
.PHONY : UI/sources/info_page.i

# target to preprocess a source file
UI/sources/info_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/info_page.cpp.i
.PHONY : UI/sources/info_page.cpp.i

UI/sources/info_page.s: UI/sources/info_page.cpp.s
.PHONY : UI/sources/info_page.s

# target to generate assembly for a file
UI/sources/info_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/info_page.cpp.s
.PHONY : UI/sources/info_page.cpp.s

UI/sources/loading_app_page.o: UI/sources/loading_app_page.cpp.o
.PHONY : UI/sources/loading_app_page.o

# target to build an object file
UI/sources/loading_app_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/loading_app_page.cpp.o
.PHONY : UI/sources/loading_app_page.cpp.o

UI/sources/loading_app_page.i: UI/sources/loading_app_page.cpp.i
.PHONY : UI/sources/loading_app_page.i

# target to preprocess a source file
UI/sources/loading_app_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/loading_app_page.cpp.i
.PHONY : UI/sources/loading_app_page.cpp.i

UI/sources/loading_app_page.s: UI/sources/loading_app_page.cpp.s
.PHONY : UI/sources/loading_app_page.s

# target to generate assembly for a file
UI/sources/loading_app_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/loading_app_page.cpp.s
.PHONY : UI/sources/loading_app_page.cpp.s

UI/sources/menu_page.o: UI/sources/menu_page.cpp.o
.PHONY : UI/sources/menu_page.o

# target to build an object file
UI/sources/menu_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/menu_page.cpp.o
.PHONY : UI/sources/menu_page.cpp.o

UI/sources/menu_page.i: UI/sources/menu_page.cpp.i
.PHONY : UI/sources/menu_page.i

# target to preprocess a source file
UI/sources/menu_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/menu_page.cpp.i
.PHONY : UI/sources/menu_page.cpp.i

UI/sources/menu_page.s: UI/sources/menu_page.cpp.s
.PHONY : UI/sources/menu_page.s

# target to generate assembly for a file
UI/sources/menu_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/menu_page.cpp.s
.PHONY : UI/sources/menu_page.cpp.s

UI/sources/page.o: UI/sources/page.cpp.o
.PHONY : UI/sources/page.o

# target to build an object file
UI/sources/page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/page.cpp.o
.PHONY : UI/sources/page.cpp.o

UI/sources/page.i: UI/sources/page.cpp.i
.PHONY : UI/sources/page.i

# target to preprocess a source file
UI/sources/page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/page.cpp.i
.PHONY : UI/sources/page.cpp.i

UI/sources/page.s: UI/sources/page.cpp.s
.PHONY : UI/sources/page.s

# target to generate assembly for a file
UI/sources/page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/page.cpp.s
.PHONY : UI/sources/page.cpp.s

UI/sources/settings_page.o: UI/sources/settings_page.cpp.o
.PHONY : UI/sources/settings_page.o

# target to build an object file
UI/sources/settings_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/settings_page.cpp.o
.PHONY : UI/sources/settings_page.cpp.o

UI/sources/settings_page.i: UI/sources/settings_page.cpp.i
.PHONY : UI/sources/settings_page.i

# target to preprocess a source file
UI/sources/settings_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/settings_page.cpp.i
.PHONY : UI/sources/settings_page.cpp.i

UI/sources/settings_page.s: UI/sources/settings_page.cpp.s
.PHONY : UI/sources/settings_page.s

# target to generate assembly for a file
UI/sources/settings_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/settings_page.cpp.s
.PHONY : UI/sources/settings_page.cpp.s

UI/sources/window.o: UI/sources/window.cpp.o
.PHONY : UI/sources/window.o

# target to build an object file
UI/sources/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/window.cpp.o
.PHONY : UI/sources/window.cpp.o

UI/sources/window.i: UI/sources/window.cpp.i
.PHONY : UI/sources/window.i

# target to preprocess a source file
UI/sources/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/window.cpp.i
.PHONY : UI/sources/window.cpp.i

UI/sources/window.s: UI/sources/window.cpp.s
.PHONY : UI/sources/window.s

# target to generate assembly for a file
UI/sources/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/window.cpp.s
.PHONY : UI/sources/window.cpp.s

UI/sources/window_state.o: UI/sources/window_state.cpp.o
.PHONY : UI/sources/window_state.o

# target to build an object file
UI/sources/window_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/window_state.cpp.o
.PHONY : UI/sources/window_state.cpp.o

UI/sources/window_state.i: UI/sources/window_state.cpp.i
.PHONY : UI/sources/window_state.i

# target to preprocess a source file
UI/sources/window_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/window_state.cpp.i
.PHONY : UI/sources/window_state.cpp.i

UI/sources/window_state.s: UI/sources/window_state.cpp.s
.PHONY : UI/sources/window_state.s

# target to generate assembly for a file
UI/sources/window_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/UI/sources/window_state.cpp.s
.PHONY : UI/sources/window_state.cpp.s

evolution/sources/Bot.o: evolution/sources/Bot.cpp.o
.PHONY : evolution/sources/Bot.o

# target to build an object file
evolution/sources/Bot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Bot.cpp.o
.PHONY : evolution/sources/Bot.cpp.o

evolution/sources/Bot.i: evolution/sources/Bot.cpp.i
.PHONY : evolution/sources/Bot.i

# target to preprocess a source file
evolution/sources/Bot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Bot.cpp.i
.PHONY : evolution/sources/Bot.cpp.i

evolution/sources/Bot.s: evolution/sources/Bot.cpp.s
.PHONY : evolution/sources/Bot.s

# target to generate assembly for a file
evolution/sources/Bot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Bot.cpp.s
.PHONY : evolution/sources/Bot.cpp.s

evolution/sources/Eat.o: evolution/sources/Eat.cpp.o
.PHONY : evolution/sources/Eat.o

# target to build an object file
evolution/sources/Eat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Eat.cpp.o
.PHONY : evolution/sources/Eat.cpp.o

evolution/sources/Eat.i: evolution/sources/Eat.cpp.i
.PHONY : evolution/sources/Eat.i

# target to preprocess a source file
evolution/sources/Eat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Eat.cpp.i
.PHONY : evolution/sources/Eat.cpp.i

evolution/sources/Eat.s: evolution/sources/Eat.cpp.s
.PHONY : evolution/sources/Eat.s

# target to generate assembly for a file
evolution/sources/Eat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Eat.cpp.s
.PHONY : evolution/sources/Eat.cpp.s

evolution/sources/Empty.o: evolution/sources/Empty.cpp.o
.PHONY : evolution/sources/Empty.o

# target to build an object file
evolution/sources/Empty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Empty.cpp.o
.PHONY : evolution/sources/Empty.cpp.o

evolution/sources/Empty.i: evolution/sources/Empty.cpp.i
.PHONY : evolution/sources/Empty.i

# target to preprocess a source file
evolution/sources/Empty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Empty.cpp.i
.PHONY : evolution/sources/Empty.cpp.i

evolution/sources/Empty.s: evolution/sources/Empty.cpp.s
.PHONY : evolution/sources/Empty.s

# target to generate assembly for a file
evolution/sources/Empty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Empty.cpp.s
.PHONY : evolution/sources/Empty.cpp.s

evolution/sources/Object.o: evolution/sources/Object.cpp.o
.PHONY : evolution/sources/Object.o

# target to build an object file
evolution/sources/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Object.cpp.o
.PHONY : evolution/sources/Object.cpp.o

evolution/sources/Object.i: evolution/sources/Object.cpp.i
.PHONY : evolution/sources/Object.i

# target to preprocess a source file
evolution/sources/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Object.cpp.i
.PHONY : evolution/sources/Object.cpp.i

evolution/sources/Object.s: evolution/sources/Object.cpp.s
.PHONY : evolution/sources/Object.s

# target to generate assembly for a file
evolution/sources/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Object.cpp.s
.PHONY : evolution/sources/Object.cpp.s

evolution/sources/Poison.o: evolution/sources/Poison.cpp.o
.PHONY : evolution/sources/Poison.o

# target to build an object file
evolution/sources/Poison.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Poison.cpp.o
.PHONY : evolution/sources/Poison.cpp.o

evolution/sources/Poison.i: evolution/sources/Poison.cpp.i
.PHONY : evolution/sources/Poison.i

# target to preprocess a source file
evolution/sources/Poison.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Poison.cpp.i
.PHONY : evolution/sources/Poison.cpp.i

evolution/sources/Poison.s: evolution/sources/Poison.cpp.s
.PHONY : evolution/sources/Poison.s

# target to generate assembly for a file
evolution/sources/Poison.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Poison.cpp.s
.PHONY : evolution/sources/Poison.cpp.s

evolution/sources/Wall.o: evolution/sources/Wall.cpp.o
.PHONY : evolution/sources/Wall.o

# target to build an object file
evolution/sources/Wall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Wall.cpp.o
.PHONY : evolution/sources/Wall.cpp.o

evolution/sources/Wall.i: evolution/sources/Wall.cpp.i
.PHONY : evolution/sources/Wall.i

# target to preprocess a source file
evolution/sources/Wall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Wall.cpp.i
.PHONY : evolution/sources/Wall.cpp.i

evolution/sources/Wall.s: evolution/sources/Wall.cpp.s
.PHONY : evolution/sources/Wall.s

# target to generate assembly for a file
evolution/sources/Wall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/Wall.cpp.s
.PHONY : evolution/sources/Wall.cpp.s

evolution/sources/World.o: evolution/sources/World.cpp.o
.PHONY : evolution/sources/World.o

# target to build an object file
evolution/sources/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/World.cpp.o
.PHONY : evolution/sources/World.cpp.o

evolution/sources/World.i: evolution/sources/World.cpp.i
.PHONY : evolution/sources/World.i

# target to preprocess a source file
evolution/sources/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/World.cpp.i
.PHONY : evolution/sources/World.cpp.i

evolution/sources/World.s: evolution/sources/World.cpp.s
.PHONY : evolution/sources/World.s

# target to generate assembly for a file
evolution/sources/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/evolution/sources/World.cpp.s
.PHONY : evolution/sources/World.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course-paper.dir/build.make CMakeFiles/course-paper.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... course-paper"
	@echo "... UI/sources/evolution.o"
	@echo "... UI/sources/evolution.i"
	@echo "... UI/sources/evolution.s"
	@echo "... UI/sources/info_page.o"
	@echo "... UI/sources/info_page.i"
	@echo "... UI/sources/info_page.s"
	@echo "... UI/sources/loading_app_page.o"
	@echo "... UI/sources/loading_app_page.i"
	@echo "... UI/sources/loading_app_page.s"
	@echo "... UI/sources/menu_page.o"
	@echo "... UI/sources/menu_page.i"
	@echo "... UI/sources/menu_page.s"
	@echo "... UI/sources/page.o"
	@echo "... UI/sources/page.i"
	@echo "... UI/sources/page.s"
	@echo "... UI/sources/settings_page.o"
	@echo "... UI/sources/settings_page.i"
	@echo "... UI/sources/settings_page.s"
	@echo "... UI/sources/window.o"
	@echo "... UI/sources/window.i"
	@echo "... UI/sources/window.s"
	@echo "... UI/sources/window_state.o"
	@echo "... UI/sources/window_state.i"
	@echo "... UI/sources/window_state.s"
	@echo "... evolution/sources/Bot.o"
	@echo "... evolution/sources/Bot.i"
	@echo "... evolution/sources/Bot.s"
	@echo "... evolution/sources/Eat.o"
	@echo "... evolution/sources/Eat.i"
	@echo "... evolution/sources/Eat.s"
	@echo "... evolution/sources/Empty.o"
	@echo "... evolution/sources/Empty.i"
	@echo "... evolution/sources/Empty.s"
	@echo "... evolution/sources/Object.o"
	@echo "... evolution/sources/Object.i"
	@echo "... evolution/sources/Object.s"
	@echo "... evolution/sources/Poison.o"
	@echo "... evolution/sources/Poison.i"
	@echo "... evolution/sources/Poison.s"
	@echo "... evolution/sources/Wall.o"
	@echo "... evolution/sources/Wall.i"
	@echo "... evolution/sources/Wall.s"
	@echo "... evolution/sources/World.o"
	@echo "... evolution/sources/World.i"
	@echo "... evolution/sources/World.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

